version: '2'

services:
  haproxy:
    image: haproxy:1.6
    ports:
      - "80:80"
      - "443:443"
    environment:
      - BALANCE=roundrobin
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - keys:/etc/haproxy/certs
  encrypt:
    build: .
    image: nouchka/letsencrypt:cloudflare
    env_file:
      - .env
    volumes:
      - keys:/etc/letsencrypt

volumes:
  static:
    driver: local
  keys:
    driver: local
